config/routes.rb
Rails.application.routes.draw do

  resources :suggestions
  resources :reservations
    resources :cars

  get '/home',  to: 'homepage#home'
  root 'homepage#home'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  post '/users/new', to: 'users#new'

  get '/user_manage_cars',  to: 'users#user_manage_cars'
  get '/admin_manage_cars',    to: 'users#admin_manage_cars'

  get '/search_car',  to: 'reservations#search_car'
  post '/search_car',  to: 'reservations#search'

  get '/selected_car_list',  to: 'reservations#selected_car_list'
  post '/selected_car_list',  to: 'reservations#selected_car_list'

  get '/reserve_car',  to: 'reservations#reserve_car'
  post '/reserve_car',  to: 'reservations#reserve'

  get '/notify_car',  to: 'reservations#notify_car'
  post '/notify_car',  to: 'reservations#notify_car'

  get '/reserve_final',  to: 'reservations#reserve_final'
  post '/reserve_final',  to: 'reservations#reserve_final'

  get '/reserve_checkout',  to: 'reservations#checkout'
  post '/reserve_checkout',  to: 'reservations#checkout'

  get '/reserve_return',  to: 'reservations#return'
  post '/reserve_return',  to: 'reservations#return'

  get '/reserve_cancel',  to: 'reservations#cancel'
  post '/reserve_cancel',  to: 'reservations#cancel'

  get '/view_car_history',  to: 'cars#view_car_history'
  post '/view_car_history',  to: 'cars#view_car_history'

  get '/manage_reservation',  to: 'reservations#manage_reservation'
  post '/manage_reservation',  to: 'reservations#manage_reservation_list'

  get '/view_admins',  to: 'users#view_admins'
  get '/view_superadmins',  to: 'users#view_superadmins'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = self.email.downcase}

  validates :name,
            presence: true,
            length: {maximum: 80},
            format: {with: /\A[a-zA-Z ]+\z/}

  validates :email, presence: true,
            length: {maximum: 100},
            format: {with: /\A[\w\-.]+[@][a-z\d\-]+[\.[a-z\d\-]+]*[\.][a-z]+\z/i},
            uniqueness: {case_sensitive: false}

  validates :password, presence: true,
            length: {minimum: 6},
            format: {with: /(?=.*[a-zA-Z])(?=.*[0-9])/}   #must contain digit


  has_secure_password

  #Admin email is admin@ncsu.edu and password is 123456
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 @@user=0
  # GET /users
  # GET /users.json
  def index
      @users = User.where(user_type: "user").all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(session[:user_id])
    user=User.find(session[:user_id]).id
    @car=Car.all
    @reservation= Reservation.where("user_id =?",user).where("status =?","Reserved")
    if(@reservation.empty?)
      @reservation= Reservation.where("user_id =?",user).where("status =?","Checkout")
    end
  end

  # GET /users/new
  def new
    @user = User.new
    if logged_in?
      @current_user = User.find(session[:user_id])
    end


  end

  # GET /users/1/edit
  def edit
    if params[:id].empty?
      @user = User.find(session[:user_id])
    else
      @user = User.find(params[:id])
    end

  end

  # POST /users
  # POST /users.json
  def create
    if logged_in?
      @current_user = User.find(session[:user_id])
    end
    @user = User.new(user_params)
    if logged_in?
      if @current_user.user_type=="admin" or @current_user.user_type=="superadmin" and params[:acc_type] == 'admin'

        @user.user_type= "admin"
        if @user.save
          flash[:success] = (" New Admin created successfully: " + @user.name)
          if logged_in?
            redirect_to view_admins_url
          else
            redirect_to root_url
          end
        else
          render 'new'
        end
      end
      if @current_user.user_type=="admin" or @current_user.user_type=="superadmin" and params[:acc_type] == 'user'

        @user.user_type= "user"
        if @user.save
          flash[:success] = (" New User created successfully : " + @user.name)
          if logged_in?
            redirect_to users_url
          else
            redirect_to root_url
          end
        else
          render 'new'
        end
      end
      if @current_user.user_type=="superadmin" and params[:acc_type] == 'superadmin'

        @user.user_type= "superadmin"
        if @user.save
          flash[:success] = ("New Super Admin created successfully: " + @user.name)
          if logged_in? and User.find(session[:user_id]).user_type=="superadmin"
            redirect_to view_superadmins_url
          else
            redirect_to root_url
          end
        else
          render 'new'
        end
      end
      else
        @user.user_type = "user"
        if @user.save
        flash[:success] = ("Registration successful " + @user.name)
        if logged_in? and User.find(session[:user_id]).user_type=="admin"
          redirect_to view_admins_url
        else
          redirect_to root_url
        end
        else
          render 'new'
        end
    end
    end
    def view_admins
      @user = User.find(session[:user_id])
    @users= User.where(user_type:  "admin").all
    end
  def view_superadmins
    @user = User.find(session[:user_id])
    @users= User.where(user_type:  "superadmin").all
  end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:acc_id].empty?
      render 'edit'
    else
      @user= User.find(params[:acc_id])
      if @user.password_digest.empty?
        puts "hello"
      else @user.update(user_params)
        puts "rerertetretrerterteyeyte #{params[:acc_id]}"
        flash[:success] = "Update successful"
        redirect_to user_url(@user)
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @reservation=Reservation.where("user_id =?",@user.id).where("status =?","Reserved").or(Reservation.where("user_id =?",@user.id).where("status =?","Checkout"))
    if @reservation.empty?
      @user.destroy
      respond_to do |format|
        format.html {redirect_back fallback_location: root_path}
        flash[:success]= 'User was successfully destroyed.'
        format.json { head :no_content }
      end
    else

      respond_to do |format|
        format.html {redirect_back fallback_location: root_path}
        flash[:success]= 'User cannot be deleted as he is reverved with a car'
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  def admin_manage_car
    @user = User.find(session[:user_id])
  end
  def user_manage_car
    @user = User.find(session[:user_id])
  end
  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest, id: :user_password_digest %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :user_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/admin_manage_cars.html.erb
<body>
<h2>
  Manage Cars
</h2>

<ul class="list-group">
  <li class="list-group-item"><%= link_to "Add Car", new_car_url , method: "get" %></li>
  <li class="list-group-item"><%= link_to "View/Edit/Delete/History Cars", cars_path, method: "get" %></li>
</ul>
</body>

app/views/users/edit.html.erb
<h1>Update Profile</h1>
<body>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages'%>

    <%= form_for(@user) do |field| %>
        <%= field.label :name %>
        <%= field.text_field :name %>

        <%= field.label :email %>
        <%= field.email_field :email %>

        <%= field.label :password %>
        <%= field.password_field :password %>

        <%= field.label :password_confirmation, "Password Confirmation" %>
        <%= field.password_field :password_confirmation %>
        <%= hidden_field_tag(:acc_id, @user.id) %>
        <%= field.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</body>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of users</h1>
<center>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Type</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Delete this user', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= hidden_field_tag(:u_acc_id, user.id) %>
        <td><%= link_to 'Edit', edit_user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>


<br>
<h2>
<%= link_to 'Create a New User',{:controller => "users", :action => "new", :acc_type => "user"} %>
</h2>
<br>

app/views/users/new.html.erb
<% if logged_in? %>
<% if logged_in? and params[:acc_type]=='superadmin'%>
    <h1>Create new super admin</h1>
    <% end %>
<% if logged_in? and params[:acc_type]=='admin'%>
        <h1>Create new admin user</h1>

    <% end %>
<% if logged_in? and params[:acc_type]=='user'%>
    <h1>Create a new user</h1>
    <% end %>
<% else %>
        <h1>Sign up</h1>
<% end %>

<body>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages'%>
    <%= form_for @user do |field| %>
        <%= field.label :name %>
        <%= field.text_field :name %>

        <%= field.label :email %>
        <%= field.email_field :email %>

        <%= field.label :password %>
        <%= field.password_field :password %>

        <%= field.label :password_confirmation, "Password Confirmation" %>
        <%= field.password_field :password_confirmation %>
        <% if params[:acc_type].nil? %>
            <%= hidden_field_tag(:acc_type, 'user') %>
            <%= field.submit "Sign Up", class: "btn btn-primary" %>
        <% end %>
        <% if logged_in? and params[:acc_type]=='superadmin'%>
            <%= hidden_field_tag(:acc_type, 'superadmin') %>
            <%= field.submit "Create Super Admin account", class: "btn btn-primary" %>
        <% end %>
        <%if params[:acc_type]=='admin'%>
                <%= hidden_field_tag(:acc_type, 'admin') %>
                <%= field.submit "Create Admin account", class: "btn btn-primary" %>
        <% end %>
        <% if params[:acc_type]=='user' %>
            <%= hidden_field_tag(:acc_type, 'user') %>
            <%= field.submit "Create User account", class: "btn btn-primary" %>
         <% end %>
    <% end %>
  </div>
</div>
</body>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<body>
<h2>
  Welcome <%= @user.name %>!
</h2>
<% if !@reservation.empty? %>
<h1>
  Your Bookings
</h1>
    <p> Note: Date format is YYYY/MM/DD</p>
<table>
  <thead>
  <tr>
    <th>Location</th>
    <th>Car Name</th>
    <th>Car Company</th>
    <th>Car Type</th>
    <th>Checkout Date</th>
    <th>Checkout Time</th>
    <th>Return Date</th>
    <th>Return Time</th>
    <th colspan =2> Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @reservation.each do |selectedcars| %>
      <tr>
        <% car=Car.find(selectedcars.car_id) %>
        <td><%= car.location %></td>
        <td><%= car.model %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.style %></td>
        <td><%= selectedcars.checkout_date %></td>
        <td><%= selectedcars.checkout_time.strftime("%I:%M%p") %></td>
        <td><%= selectedcars.return_date %></td>
        <td><%= selectedcars.return_time.strftime("%I:%M%p") %></td>
        <% if selectedcars.status=="Reserved" %>
          Current Time:  <%=  Time.now.to_time.strftime("%I:%M%p") %>,  You can only checkout after checkout time is reached. Please
            keep refreshing the page!
            <% if selectedcars.checkout_time.hour  <=  Time.now.hour and selectedcars.checkout_time.min  <=  Time.now.min %>
            <td><%= link_to 'Checkout',reserve_checkout_path %></td>
            <% end %>
            <td><%= link_to 'Cancel Reservation',reserve_cancel_path %></td>
        <% elsif selectedcars.status=="Checkout" %>
            <td><%= link_to 'Return',reserve_return_path %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<br>
<br>

<ul class="list-group">
  <% if @user.user_type=="superadmin" %>
      <li class="list-group-item"><%= link_to "Add Super Admins",{:controller => "users", :action => "new", :acc_type => "superadmin"}%></li>
      <li class="list-group-item"><%= link_to "View Super Admins", view_superadmins_url , method: "get" %></li>
      <% end %>
  <% if @user.user_type=="admin" or @user.user_type=="superadmin" %>
      <li class="list-group-item"><%= link_to "Add Admin", {:controller => "users", :action => "new", :acc_type => "admin"} %></li>
      <% if @user.user_type=="admin" or @user.user_type!="superadmin" %>
          <li class="list-group-item"><%= link_to "View Admins", view_admins_url , method: "get" %></li>
         <% else %>
          <li class="list-group-item"><%= link_to "View/Delete Admins", view_admins_url , method: "get" %></li>
          <% end %>
      <li class="list-group-item"><%= link_to "Manage Cars (Add/View/Edit/Delete/Check history) ", admin_manage_cars_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Manage Users", users_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Manage Reservations of users", manage_reservation_path , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Make Reservation for User", search_car_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Review Suggestion", suggestions_path , method: "get" %></li>
   <% else %>
      <li class="list-group-item"><%= link_to "Make a Reservation", search_car_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "My Reservation History", reservation_url , method: "get" %></li>
      <li class="list-group-item"><%= link_to "Make Suggetion", new_suggestion_url , method: "get" %></li>
<%end%>
</ul>
</body>
</html>

app/views/users/user_manage_cars.html.erb
<body>
<h2>
  Manage Car User
</h2>

<ul class="list-group">
  <li class="list-group-item"><%= link_to "View Cars", cars_path %></li>
  <li class="list-group-item"><%= link_to "Reserve a Car", search_car_url , method: "get" %></li>
</ul>

</body>

app/views/users/view_admins.html.erb
<center>
<p id="notice"><%= notice %></p>

<h1>List of admins</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th>Actions</th>


  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_type %></td>
        <% if user.id!=@user.id%>
            <td><%= link_to 'Delete this admin', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>


<br>
</center>

app/views/users/view_superadmins.html.erb
<center>
<p id="notice"><%= notice %></p>

<h1>List of Super Admins</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>

  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_type %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
</center>