config/routes.rb
Rails.application.routes.draw do

  resources :suggestions
  resources :reservations
    resources :cars

  get '/home',  to: 'homepage#home'
  root 'homepage#home'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  post '/users/new', to: 'users#new'

  get '/user_manage_cars',  to: 'users#user_manage_cars'
  get '/admin_manage_cars',    to: 'users#admin_manage_cars'

  get '/search_car',  to: 'reservations#search_car'
  post '/search_car',  to: 'reservations#search'

  get '/selected_car_list',  to: 'reservations#selected_car_list'
  post '/selected_car_list',  to: 'reservations#selected_car_list'

  get '/reserve_car',  to: 'reservations#reserve_car'
  post '/reserve_car',  to: 'reservations#reserve'

  get '/notify_car',  to: 'reservations#notify_car'
  post '/notify_car',  to: 'reservations#notify_car'

  get '/reserve_final',  to: 'reservations#reserve_final'
  post '/reserve_final',  to: 'reservations#reserve_final'

  get '/reserve_checkout',  to: 'reservations#checkout'
  post '/reserve_checkout',  to: 'reservations#checkout'

  get '/reserve_return',  to: 'reservations#return'
  post '/reserve_return',  to: 'reservations#return'

  get '/reserve_cancel',  to: 'reservations#cancel'
  post '/reserve_cancel',  to: 'reservations#cancel'

  get '/view_car_history',  to: 'cars#view_car_history'
  post '/view_car_history',  to: 'cars#view_car_history'

  get '/manage_reservation',  to: 'reservations#manage_reservation'
  post '/manage_reservation',  to: 'reservations#manage_reservation_list'

  get '/view_admins',  to: 'users#view_admins'
  get '/view_superadmins',  to: 'users#view_superadmins'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  #before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  @@count=0
  @@count1=0
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    user=User.find(session[:user_id]).id
    @showing_reservation=Reservation.where("user_id =?",user)
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation }
        flash[:success]= 'Reservation was successfully created.'
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def search_car
    @cars=Car.new
    if @@count==1
      @selectedcars=@@req_cars
    else
    end
    # #debugger
  end

  def search
    @car = Car.new(car_parameters)
    @@req_cars = Car.all
    # #debugger
    puts("#{@car.location}")
    if @car.location!=""
      @@req_cars = @@req_cars.where(location: @car.location).all
    end
    if @car.model!=""
      @@req_cars = @@req_cars.where(model: @car.model).all
    end
    if @car.manufacturer != ""
      @@req_cars = @@req_cars.where(manufacturer: @car.manufacturer).all
    end
    if @car.style != ""
      @@req_cars = @@req_cars.where(style: @car.style).all
    end
    @selectedcars=@@req_cars
    @@count=1
    redirect_to search_car_path
    #redirect_to selected_car_list_path
    #redirect_to :back
    #redirect_to :controller => 'reservations', :action => 'search', :param_a => @selectedcars

  end

  def notify_car
    @carrr=params[:car]
    @cardetails=Car.where("id =?",@carrr)
    email=Emailto.new
    email.user_id=User.find(session[:user_id]).id
    email.name=User.find(session[:user_id]).name
    email.email=User.find(session[:user_id]).email
    email.car_id=@carrr
    @cardetails.each{|x|
      email.model=x.model
      email.manufacturer=x.manufacturer
      email.lic_no=x.lic_no
      email.hourly_rate=x.hourly_rate
      email.style=x.style
    }
    email.save
    redirect_to search_car_path
  end

  def car_parameters
    params.require(:car).permit(:location, :model,:manufacturer, :style)
  end

  def reservation_parameters
    if User.find(session[:user_id]).user_type=="admin"
      params.require(:reservation).permit(:checkout_date, :checkout_time,:return_date, :return_time, :user_id)
    elsif User.find(session[:user_id]).user_type=="superadmin"
      params.require(:reservation).permit(:checkout_date, :checkout_time,:return_date, :return_time, :user_id)
    else
      params.require(:reservation).permit(:checkout_date, :checkout_time,:return_date, :return_time)
    end
  end

  def manage_user_parameters
    params.require(:user).permit(:id)
  end

  def selected_car_list
    @selectedcars=@@req_cars
  end

  def reserve_car
    @reservationcar = Reservation.new
    @carrr=params[:car]
    puts "#{@carrr} hello"
    @carselected=Car.all
    @carselected = @carselected.where(id: params[:car])
    @user = User.find(session[:user_id])
    @user_list=User.where("user_type =?","user")
    @reservation=Reservation.where("user_id =?",User.find(session[:user_id]).id).where("status =?","Reserved")
    if @reservation.empty?
      @reservation=Reservation.where("user_id =?",User.find(session[:user_id]).id).where("status =?","Checkout")
    end
    if @reservation.empty?
    else
      respond_to do |format|
        format.html {redirect_back fallback_location: root_path}
        flash[:danger]='You Have Already Reserved A Car'
        format.json { head :no_content }
      end
    end
    #redirect_to reserve_car_path
    #@carselected = Car.find(params[:car])
  end

  def reserve
    #puts "in reserve"
    #puts "in reserve"
    @reservation = Reservation.new(reservation_parameters)
    @selected_car_id=params[:car_id]
    @useradmin=User.find(session[:user_id]).user_type
    if @useradmin == "admin"
      puts "hii: #{@reservation.user_id} "
      @selected_user_id=@reservation.user_id
      if @selected_user_id.nil?
        respond_to do |format|
          format.html { redirect_to search_car_path, notice: 'Please Select User while selecting timings' }
          format.json { head :no_content }
        end
        else
        @selected_hourly_rate=params[:hourly_rate]
        @reservation.car_id=@selected_car_id
        @reservation.user_id=@selected_user_id
        @reservation.cost=@selected_hourly_rate
        @reservation.status="Reserved"
        @reservation.save
      end
    elsif @useradmin == "superadmin"
      puts "hii: #{@reservation.user_id} "
      @selected_user_id=@reservation.user_id
      if @selected_user_id.nil?
        respond_to do |format|
          format.html { redirect_to search_car_path, notice: 'Please Select User while selecting timings' }
          format.json { head :no_content }
        end
      else
        @selected_hourly_rate=params[:hourly_rate]
        @reservation.car_id=@selected_car_id
        @reservation.user_id=@selected_user_id
        @reservation.cost=@selected_hourly_rate
        @reservation.status="Reserved"
        @reservation.save
      end
    else
      @selected_user_id=User.find(session[:user_id]).id
      @selected_hourly_rate=params[:hourly_rate]
      @reservation.car_id=@selected_car_id
      @reservation.user_id=@selected_user_id
      @reservation.cost=@selected_hourly_rate
      @reservation.status="Reserved"
      @reservation.save
    end
  end

  def reserve_final
    require 'time'
    require 'date'
    @reservation = Reservation.new(reservation_parameters)

    @localcheckoutdate=@reservation.checkout_date
    @localcheckouttime=@reservation.checkout_time
    @localreturntime=@reservation.return_time
    @localreturndate=@reservation.return_date

    @present_time = Time.now
    @c_time= @localcheckouttime.hour + @localcheckouttime.min/60.0;
    @r_time= @localreturntime.hour + @localreturntime.min/60.0;
    @rental_hours= @r_time - @c_time

    @p_time = Time.now.hour+ Time.now.min/60.0

    if @localcheckoutdate -@present_time.to_date >7
      respond_to do |format|
        format.html {redirect_back fallback_location: root_path }
        flash[:danger]= 'Cannot reserve a car more than a week away from now!'
        format.json { head :no_content }
      end
    else
      if @localreturndate < @present_time.to_date or @localcheckoutdate < @present_time.to_date
        respond_to do |format|
          format.html {redirect_back fallback_location: root_path }
          flash[:danger]= 'Choose Future Dates!'
          format.json { head :no_content }
        end

      else
        if @localreturndate - @localcheckoutdate >1
          respond_to do |format|
            format.html {redirect_back fallback_location: root_path }
            flash[:danger]= "Return Day cannot be more than one day apart from Checkout Date!"
            format.json { head :no_content }
          end

        else
          if @localreturndate -@localcheckoutdate ==1
            if @r_time<11
              @r_time = @r_time + 24
            end
          end
          if @localreturndate == @localcheckoutdate and @c_time > @r_time
            respond_to do |format|
              format.html {redirect_back fallback_location: root_path }
              flash[:danger]= "Checkout time cannot be ahead of return time!"
              format.json { head :no_content }
            end

          elsif (@r_time- @c_time >10) or (@r_time - @c_time <1)
            respond_to do |format|
              format.html {redirect_back fallback_location: root_path }
              flash[:danger] = "The minimum rental period is 1 hour and the maximum is 10 hours"
              format.json { head :no_content }
            end
          else
            @somedate = DateTime.new(@localcheckouttime.to_i)
            @selected_car_id=params[:car_id]
            @useradmin=User.find(session[:user_id]).user_type
            if @useradmin == "admin"
              puts "hii: #{@reservation.user_id} "
              @selected_user_id=@reservation.user_id
              if @selected_user_id.nil?
                respond_to do |format|
                  format.html {redirect_back fallback_location: root_path }
                  flash[:danger] = 'Please Select User while selecting timings'
                  format.json { head :no_content }
                end
              else

                @showing_reservation=Reservation.where("user_id =? AND status=?",@reservation.user_id, "Reserved")
                puts "asfklasjfaskljflasjfnlasjflasnf :: #{@showing_reservation.count}"
                if @showing_reservation.count > 0
                  respond_to do |format|
                    format.html { redirect_back fallback_location: root_path}
                    flash[:danger] = 'User already has a car reserved!'
                    format.json { head :no_content }
                  end
                else
                  @selected_hourly_rate=params[:hourly_rate].to_f * (@r_time - @c_time)
                  @reservation.car_id=@selected_car_id
                  @reservation.user_id=@selected_user_id
                  @reservation.cost=@selected_hourly_rate
                  @reservation.status="Reserved"
                  @reservation.save
                end
              end

            elsif @useradmin == "superadmin"
              puts "hii: #{@reservation.user_id} "
              @selected_user_id=@reservation.user_id
              if @selected_user_id.nil?
                respond_to do |format|

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.number_field :car_id, id: :reservation_car_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :reservation_user_id %>
  </div>

  <div class="field">
    <%= form.label :checkout_date %>
    <%= form.date_select :checkout_date, id: :reservation_checkout_date %>
  </div>

  <div class="field">
    <%= form.label :return_date %>
    <%= form.date_select :return_date, id: :reservation_return_date %>
  </div>

  <div class="field">
    <%= form.label :checkout_time %>
    <%= form.time_select :checkout_time, id: :reservation_checkout_time %>
  </div>

  <div class="field">
    <%= form.label :return_time %>
    <%= form.time_select :return_time, id: :reservation_return_time %>
  </div>

  <div class="field">
    <%= form.label :actual_return_time %>
    <%= form.time_select :actual_return_time, id: :reservation_actual_return_time %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: :reservation_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>User</th>
      <th>Checkout date</th>
      <th>Return date</th>
      <th>Checkout time</th>
      <th>Return time</th>
      <th>Actual return time</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.car_id %></td>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.checkout_date %></td>
        <td><%= reservation.return_date %></td>
        <td><%= reservation.checkout_time %></td>
        <td><%= reservation.return_time %></td>
        <td><%= reservation.actual_return_time %></td>
        <td><%= reservation.cost %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/manage_reservation.erb
<%= form_for @user, url: manage_reservation_path do |f| %>

    <%= f.label :user_name %>
    <%= f.select :id, options_from_collection_for_select(@user_list.all{ |o| o.name}, :id, :name), {:prompt => "Select.."}%>
    <%= f.submit "Select", class: "btn btn-primary" %>

<% end %>
<% if !@selecteduser.nil? %>
<p id="notice"><%= notice %></p>


<table>
  <thead>
  <tr>
    <th>Location</th>
    <th>Car Name</th>
    <th>Car Company</th>
    <th>Car Type</th>
    <th>Checkout Date</th>
    <th>Checkout Time</th>
    <th>Return Date</th>
    <th>Return Time</th>
    <th>Price</th>
    <th> Actions</th>
  </tr>
  </thead>

  <tbody>
  <% if !@selecteduser.nil? then %>
      <% @selecteduser.each do |reservation| %>
          <tr>
            <% car=Car.find(reservation.car_id) %>
            <td><%= car.location %></td>
            <td><%= car.model %></td>
            <td><%= car.manufacturer %></td>
            <td><%= car.style %></td>
            <td><%= reservation.checkout_date %></td>
            <td><%= reservation.checkout_time.strftime("%I:%M%p") %></td>
            <td><%= reservation.return_date %></td>
            <td><%= reservation.return_time.strftime("%I:%M%p") %></td>
            <td><%= reservation.cost %></td>
            <% if reservation.status=="Avaliable" %>
            <td> </td>
            <% elsif reservation.status=="Checkout" %>
                <td><%= link_to 'Return',"#" %></td>
             <% else %>
                <td><%= link_to 'Checkout',"#" %></td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/reserve_car.erb
<style>
  .datetime select:nth-child(1){
    width: 130px;
    text-indent: 15px;
  }

  .datetime select:nth-child(2) {
    width: 200px;
    text-indent: 5px;
  }

  .datetime select:nth-child(3) {
    width: 110px;
    text-indent: 15px;
  }
</style>


<h1>Selected Car</h1>
<center>
  <table>
    <thead>
    <tr>
      <th>Location</th>
      <th>Car Name</th>
      <th>Car Company</th>
      <th>Car Type</th>
      <th>Car Status</th>
      <th>Car Hourly Charges</th>
    </tr>
    </thead>

    <tbody>
    <% @carselected.each do |selectedcars| %>
        <tr>
          <td><%= selectedcars.location %></td>
          <td><%= selectedcars.model %></td>
          <td><%= selectedcars.manufacturer %></td>
          <td><%= selectedcars.style %></td>
          <td><%= selectedcars.status %></td>
          <td><%= selectedcars.hourly_rate %></td>
          <% @car_id = selectedcars.id %>
          <% @hourly_rate = selectedcars.hourly_rate %>
        </tr>
    <% end %>
    </tbody>
  </table>
</center>
<br>
<h1>Select Timings</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @reservationcar, url: reserve_final_path do |f| %>
        <% if @user.user_type!="user"%>
            <%= f.label :username %>
            <%= f.select :user_id, options_from_collection_for_select(@user_list.all{|o| o.name}, :id, :name), {:prompt => ""}%>
        <% end %>
        <%= f.label :checkout_date %>
        <span class="datetime"><%= f.date_select :checkout_date %></span>
        <%= f.label :checkout_time %>
        <span class="datetime"><%= f.time_select :checkout_time, {ampm: true, ignore_date: true} %></span>
        <%= f.label :return_date %>
        <span class="datetime"> <%= f.date_select :return_date %> </span>
        <%= f.label :return_time %>
        <span class="datetime"><%= f.time_select :return_time, {ampm: true, ignore_date: true} %></span>
        <%= f.submit "Reserve Car", id:"reserve_car1", class: "btn btn-primary" %>
        <%= hidden_field_tag 'car_id',  @car_id %>
        <%= hidden_field_tag 'hourly_rate',  @hourly_rate %>
        <%= hidden_field_tag 'hourly_rate',  @hourly_rate %>
    <% end %>
  </div>
</div>

app/views/reservations/reserve_final.erb
<h1> Booking Successful</h1>

app/views/reservations/search_car.erb
<h1>Search Car</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for @cars, url: search_car_path do |f| %>

        <%= f.label :location %>
        <%= f.select :location, options_from_collection_for_select(Car.all.to_a.uniq{ |o| o.location}, :location, :location), {:prompt => "Select.."}%>
        <%= f.label :car %>
        <%= f.select :model, options_from_collection_for_select(Car.all.to_a.uniq{ |o| o.model}, :model, :model), {:prompt => "Select.."}%>
        <%= f.label :manufacturer %>
        <%= f.select :manufacturer, options_from_collection_for_select(Car.all.to_a.uniq{ |o| o.manufacturer}, :manufacturer, :manufacturer), {:prompt => "Select.."}%>
        <%= f.label :car_type %>
        <%= f.select :style, options_from_collection_for_select(Car.all.to_a.uniq{ |o| o.style}, :style, :style), {:prompt => "Select.."}%>
        <%= f.submit "Search", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>
<br>
<br>
<center>
  <p id="notice"><%= notice %></p>
<table>
  <thead>
  <tr>
    <th>Location</th>
    <th>Car Name</th>
    <th>Car Company</th>
    <th>Car Type</th>
    <th>Car Status</th>
    <th>Car Hourly Charges</th>
  </tr>
  </thead>

  <tbody>
  <% if !@selectedcars.nil? then
     else
       @selectedcars=Car.all
     end %>
  <% @selectedcars.each do |selectedcars| %>
  <tr>
    <td><%= selectedcars.location %></td>
    <td><%= selectedcars.model %></td>
    <td><%= selectedcars.manufacturer %></td>
    <td><%= selectedcars.style %></td>
    <td><%= selectedcars.status %></td>
    <td><%= selectedcars.hourly_rate %></td>
    <% if selectedcars.status=="Avaliable" %>
        <td><%= link_to 'Reserve', {:controller => "reservations", :action => "reserve_car", :car => selectedcars.id}%></td>
    <% elsif selectedcars.status=="Checkout" %>
        <td><%= link_to 'Notify ', {:controller => "reservations", :action => "notify_car", :car => selectedcars.id}%></td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
</table>
</center>
<br>

app/views/reservations/selected_car_list.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
  <tr>
    <th>Car</th>
    <th>User</th>
    <th>Checkout date</th>
    <th>Return date</th>
    <th>Checkout time</th>
    <th>Return time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @selectedcars.each do |selectedcars| %>
      <tr>
        <td><%= selectedcars.location %></td>
        <td><%= selectedcars.model %></td>
        <td><%= selectedcars.manufacturer %></td>
        <td><%= selectedcars.style %></td>
        <td><%= selectedcars.status %></td>
        <td><%= selectedcars.hourly_rate %></td>
        <% if selectedcars.status=="AVALIABLE" %>
            <td><%= link_to 'Checkout', "#" %></td>
            <td><%= link_to 'Reserve', "#" %></td>
        <% else %>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/reservations/show.html.erb
<h1> Your Reservation History </h1>

<table>
  <thead>
  <tr>
    <th>Car Model</th>
    <th>Car Manufacturer</th>
    <th>Checkout Date</th>
    <th>Checkout Time</th>
    <th>Return Date</th>
    <th>Return Time</th>
    <th>Price</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <tr>

    <% @showing_reservation.each do |reservation| %>
        <% car=Car.find(reservation.car_id) %>
        <td><%= car.model %></td>
        <td><%= car.manufacturer %></td>
        <td><%= reservation.checkout_date %></td>
        <td><%= reservation.checkout_time.strftime("%I:%M%p") %></td>
        <td><%= reservation.return_date %></td>
        <td><%= reservation.return_time.strftime("%I:%M%p") %></td>
        <td><%= reservation.cost %></td>
        <% if reservation.status=="Reserved" %>
            <td> Reserved </td>
        <% elsif reservation.status=="Checkout" %>
            <td> In Service </td>
        <% else %>
            <td> Completed </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>