config/routes.rb
Rails.application.routes.draw do

  resources :suggestions
  resources :reservations
    resources :cars

  get '/home',  to: 'homepage#home'
  root 'homepage#home'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  post '/users/new', to: 'users#new'

  get '/user_manage_cars',  to: 'users#user_manage_cars'
  get '/admin_manage_cars',    to: 'users#admin_manage_cars'

  get '/search_car',  to: 'reservations#search_car'
  post '/search_car',  to: 'reservations#search'

  get '/selected_car_list',  to: 'reservations#selected_car_list'
  post '/selected_car_list',  to: 'reservations#selected_car_list'

  get '/reserve_car',  to: 'reservations#reserve_car'
  post '/reserve_car',  to: 'reservations#reserve'

  get '/notify_car',  to: 'reservations#notify_car'
  post '/notify_car',  to: 'reservations#notify_car'

  get '/reserve_final',  to: 'reservations#reserve_final'
  post '/reserve_final',  to: 'reservations#reserve_final'

  get '/reserve_checkout',  to: 'reservations#checkout'
  post '/reserve_checkout',  to: 'reservations#checkout'

  get '/reserve_return',  to: 'reservations#return'
  post '/reserve_return',  to: 'reservations#return'

  get '/reserve_cancel',  to: 'reservations#cancel'
  post '/reserve_cancel',  to: 'reservations#cancel'

  get '/view_car_history',  to: 'cars#view_car_history'
  post '/view_car_history',  to: 'cars#view_car_history'

  get '/manage_reservation',  to: 'reservations#manage_reservation'
  post '/manage_reservation',  to: 'reservations#manage_reservation_list'

  get '/view_admins',  to: 'users#view_admins'
  get '/view_superadmins',  to: 'users#view_superadmins'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord

  validates :model, presence: true
  validates :manufacturer, presence: true
  validates :status, presence: true
  validates :lic_no, presence: true, uniqueness: true
  validates :hourly_rate, presence: true
  validates :style, presence: true
  validates :location, presence: true

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @user = User.find(session[:user_id])

  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    set_car
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    @car=Car.find(params[:id])
    set_car
  end

  def view_car_history
    puts "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd #{params[:acc_type]}"
    @carreservation= Reservation.where("car_id =?",params[:acc_type])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    if params[:sgg_no].nil?
    else
       @suggestions=Suggestion.where("id =?",params[:sgg_no])
       @suggestions.delete_all
    end
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car}
        flash[:success]='Car was successfully created.'
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    set_car
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car}
        flash[:success]= 'Car was successfully updated.'
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    set_car
    @reservation=Reservation.where("car_id =?",set_car.id).where("status =?","Reserved").or(Reservation.where("car_id =?",set_car.id).where("status =?","Checkout"))
    if(@reservation.empty?)
      @car.destroy
      respond_to do |format|
        format.html { redirect_to cars_url}
        flash[:success]= 'Car was successfully destroyed!'

        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to cars_url}
        flash[:danger]= 'Car cannot be deleted as it is reserved by someone!'
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :manufacturer, :status, :lic_no, :hourly_rate, :style, :location)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, id: :car_manufacturer %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,["Avaliable","Checkout"], id: :car_status %>
  </div>

  <div class="field">
    <%= form.label :lic_no %>
    <%= form.text_field :lic_no, id: :car_lic_no %>
  </div>

  <div class="field">
    <%= form.label :hourly_rate %>
    <%= form.number_field :hourly_rate, id: :car_hourly_rate %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.select :style,["","Sedane","SUV","LUV", ], id: :car_style %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.select :location,["","Raleigh","San Jose","New York"], id: :car_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Cars</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Manufacturer</th>
      <th>Status</th>
      <th>Lic no</th>
      <th>Hourly rate</th>
      <th>Style</th>
      <th>Location</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.status %></td>
        <td><%= car.lic_no %></td>
        <td><%= car.hourly_rate %></td>
        <td><%= car.style %></td>
        <td><%= car.location %></td>
        <td><%= link_to 'Show', car %></td>
        <% if @user.user_type=="admin" or @user.user_type=="superadmin"%>
          <td><%= link_to 'Edit', edit_car_path(car) %></td>
          <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'History',{:controller => "cars", :action => "view_car_history", :acc_type => car.id} %></td>
        <%end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', admin_manage_cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<p>
  <strong>Lic no:</strong>
  <%= @car.lic_no %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @car.hourly_rate %>
</p>

<p>
  <strong>Style:</strong>
  <%= @car.style %>
</p>

<p>
  <strong>Location:</strong>
  <%= @car.location %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/cars/view_car_history.erb
<center>
<table>
  <thead>
  <tr>
    <th>Location</th>
    <th>Car Name</th>
    <th>User</th>
    <th>Checkout Date</th>
    <th>Checkout Time</th>
    <th>Return Date</th>
    <th>Return Time</th>
    <th>Price</th>
  </tr>
  </thead>

  <tbody>
      <% @carreservation.each do |reservation| %>
          <tr>
            <% car=Car.find(reservation.car_id) %>
            <% user=User.find(reservation.user_id) %>
            <td><%= car.location %></td>
            <td><%= car.model %></td>
            <td><%= user.name %></td>
            <td><%= reservation.checkout_date %></td>
            <td><%= reservation.checkout_time %></td>
            <td><%= reservation.return_date %></td>
            <td><%= reservation.return_time %></td>
            <td><%= reservation.cost %></td>
          </tr>
      <% end %>
  </tbody>
</table>
</center>