config/routes.rb
Rails.application.routes.draw do

  resources :suggestions
  resources :reservations
    resources :cars

  get '/home',  to: 'homepage#home'
  root 'homepage#home'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  post '/users/new', to: 'users#new'

  get '/user_manage_cars',  to: 'users#user_manage_cars'
  get '/admin_manage_cars',    to: 'users#admin_manage_cars'

  get '/search_car',  to: 'reservations#search_car'
  post '/search_car',  to: 'reservations#search'

  get '/selected_car_list',  to: 'reservations#selected_car_list'
  post '/selected_car_list',  to: 'reservations#selected_car_list'

  get '/reserve_car',  to: 'reservations#reserve_car'
  post '/reserve_car',  to: 'reservations#reserve'

  get '/notify_car',  to: 'reservations#notify_car'
  post '/notify_car',  to: 'reservations#notify_car'

  get '/reserve_final',  to: 'reservations#reserve_final'
  post '/reserve_final',  to: 'reservations#reserve_final'

  get '/reserve_checkout',  to: 'reservations#checkout'
  post '/reserve_checkout',  to: 'reservations#checkout'

  get '/reserve_return',  to: 'reservations#return'
  post '/reserve_return',  to: 'reservations#return'

  get '/reserve_cancel',  to: 'reservations#cancel'
  post '/reserve_cancel',  to: 'reservations#cancel'

  get '/view_car_history',  to: 'cars#view_car_history'
  post '/view_car_history',  to: 'cars#view_car_history'

  get '/manage_reservation',  to: 'reservations#manage_reservation'
  post '/manage_reservation',  to: 'reservations#manage_reservation_list'

  get '/view_admins',  to: 'users#view_admins'
  get '/view_superadmins',  to: 'users#view_superadmins'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
<!--    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>

    </ul>-->
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Car Rental App", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in?%>
            <li><%= link_to "Home",   user_path(session[:user_id]) %></li>
            <li><%= link_to "Update Profile", edit_user_path(session[:user_id]) , method: "get" %></li>
      <% end %>
        <!--<li><%= link_to "Help",  '#' %></li>-->
        <% if logged_in?%>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to "Login", login_path, method: "get" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRentalApp2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div>
      <% flash.each do |message_type, message| %>
          <div class="alert-<%= message_type %>">
            <br>
            <ul>
              <%= message %>
            </ul>
            <br>
          </div>

      <% end %>
    </div>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>